name: Publish Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        run: echo ${{ secrets.HARBOR_TOKEN }} | docker login ${{ secrets.HARBOR_REGISTRY_DOMAIN }} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |-
              linux/arm64
          file: ./Dockerfile
          push: true
          pull: true
          tags: ${{ secrets.HARBOR_REGISTRY_DOMAIN }}/${{ secrets.HARBOR_REGISTRY_PROJECT }}/neuro-rs:main 
          # Harbor registry domain format: domain name e.g. google.com
          # Harbor registry project format: project name e.g. neuro
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}